import { Box } from 'components/mui/material'

import { AppBar } from 'app'

export const metadata = {
  title: 'MIL MEMO',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang='jp'>
    <body>
      <Box sx={{ mb: 10 }}>
        <AppBar />
      </Box>
      {children}
    </body>
  </html>
)

export default RootLayout
